#!/bin/sh
set -eu

name=$1

git init $name
git -C $name config user.email opensource@apple.com
git -C $name config user.name opensource.apple.com

found=
current=`git -C $name describe --tags || true`
if [ ! "$current" ]; then found=1; fi

releases=$(./get-releases)
cat $name-release-dates | while read version date; do
	if [ ! "$found" ]; then
		if [ "$current" = "$version" ]; then
			found=1
		fi
		continue
	fi
	release=$(echo "$releases" | ./get-release-info $name $version)
	if [ ! "$release" ]; then
		echo skipping $name $version >&2
		continue
	fi
	echo "$release" | ./commit-release $name $version $date
done
