#!/bin/sh
set -eu
awk -v prod="$1" -v prodver="$2" -v OFS='\t' -F '[<>]' '
BEGIN {
	split(prodver, v, ".")
	ver = 100 * v[1] + v[2]
	if (prod == "macos")
		prod = ver < 1009 ? "Mac OS X" : ver < 1012 ? "OS X" : "macOS"
	else if (prod == "ios")
		prod = ver < 302 ? "iPhone" : "iOS"
	else if (prod == "developer-tools")
		prod = "Developer Tools"
	else exit 2
}
key { value = $3 }
key == "version" {
	print tolower(name), name, value, "Other" | "sort | cut -f 2-"
}
key == "build" {
	printf "# %s %s %s\n", prod, prodver, value
}
key { name = key; key = "" }
/<key>/ { key = $3 }
'
