#!/bin/sh

set -eu

if [ ! "$1" ]; then
	echo "usage: $0 product branch" >&2
	exit 1
fi

start=`git -C "$1" rev-parse origin/master`
git -C "$1" rev-list --reverse "$start".."$2" | while read c; do
	git -C "$1" reset --hard $c
	git -C "$1" push -f
	git -C "$1" push -f origin "`git -C "$1" describe --tags $c`"
done
